### ISSUE TITLE
assertRegex

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#164]
Originally reported by: **Arthur Goldberg (Bitbucket: [arthurgoldberg](https://bitbucket.org/arthurgoldberg), GitHub: Unknown)**

----------------------------------------

Don't have time for good report. In brief:
six.assertRegex()¶
Alias for assertRegex() on Python 3 and assertRegexpMatches() on Python 2.

doesn't work with nosetests-2.7. I get.

ERROR: test_Specie (tests.test_specie.TestSpecie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_sim/tests/test_specie.py", line 40, in test_Specie
    six.assertRegex(self, s1.row(), 'specie\t10\..*\t0\..*\t0\..*')
AttributeError: 'module' object has no attribute 'assertRegex'

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/164

**Comment by humitos** [comment]
I'm having a similar/the same issue:

```python
>>> print(six.__version__)
1.11.0
>>> print(six.__file__)
/home/humitos/.pyenv/versions/3.6.4/envs/rtd3/lib/python3.6/site-packages/six.py
>>> six.assertRegex(r'python', r'python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/humitos/.pyenv/versions/3.6.4/envs/rtd3/lib/python3.6/site-packages/six.py", line 681, in assertRegex
    return getattr(self, _assertRegex)(*args, **kwargs)
AttributeError: 'str' object has no attribute 'assertRegex'
>>> 
```

In Python 3.6.4

```
>>> import unittest
>>> t = unittest.TestCase()
>>> t.assertRegex('python', r'python')
>>>
```
